### ISSUE TITLE
进阶设置中驱动器唤醒延时的“描述”文本漏翻译

### ISSUE THREAD

**Issue by kongmao45678** [QW-000/rpcs3_cht#2]
如题，谢谢。

**Comment by QW-000** [comment]
沒翻譯到的地方有時候是因為繁轉簡所造成的。

將 source 中的 20μs to 40μs 換成 20µs to 40µs 可解決翻譯問題。

**Comment by kongmao45678** [comment]
是需要工具吗，自己尝试一下，还是不太会弄

**Comment by QW-000** [comment]
的確需要工具，可以用 Qt 語言家。

這裡已經改好了
https://github.com/QW-000/rpcs3_cht/raw/master/qt/translations/rpcs3_zh_CN.qm
